version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - loki_net

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    #  - ./grafana/provisioning/:/etc/grafana/provisioning/
    # environment:
    #   GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
    #   GF_AUTH_ANONYMOUS_ENABLED: "true"
    #   GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    #   GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
    #   GF_AUTH_DISABLE_LOGIN_FORM: "true"
    depends_on:
      - prometheus
    networks:
      - loki_net

  # Uncomment if you want to use
  # node-exporter on the same machine

  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   ports:
  #     - 9100:9100
  #   command:
  #     - '--path.rootfs=/host'
  #   volumes:
  #     - '/:/host:ro,rslave'
  #   restart: unless-stopped
  #   networks:
  #     - loki_net

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   restart: always
  #   networks:
  #     - loki_net

  alertmanager:
    image: prom/alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    restart: unless-stopped
    volumes:
      - alertmanager_data:/data
      - ${PWD}/alertmanager/:/etc/alertmanager/
    networks:
      - loki_net

  promtail:
    image: grafana/promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ${PWD}/promtail/promtail.yml:/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - loki_net

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    restart: always
    volumes:
      - ${PWD}/loki/loki.yml:/etc/loki/local-config.yaml
    networks:
      - loki_net

networks:
  loki_net:
