global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - alertmanager/alert.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['<IP>:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['localhost:8080']
